import{createHash}from"node:crypto";import{readFileSync,writeFileSync,existsSync,mkdirSync}from"node:fs";import{dirname,resolve}from"node:path";import{assertContextSnapshotHash}from"../dist/src/context/snapshot.js";
const root=resolve(process.cwd()),sourcePath=resolve(root,"khalyon/data/phase3-diagnostic-snapshot.json"),contextPath=resolve(root,"khalyon/data/context-snapshot.json"),closurePath=resolve(root,"docs/phase3-closure-report.md"),runtimePath=resolve(root,"khalyon/data/runtime.json"),fundingPath=resolve(root,"research/funding/FROZEN_ARCHIVE_LOCK.json"),journalPath=resolve(root,"research/prospective/journal.jsonl");
const EXPECTED_DATASET="sha256:6684d0e7bfb27080430164729e6aa8ac556ac09a728f373eeb32ef3b4781abce";
const raw=readFileSync(sourcePath),snapshot=JSON.parse(raw.toString("utf8")),sourceSha256=createHash("sha256").update(raw).digest("hex"),funding=JSON.parse(readFileSync(fundingPath,"utf8"));
if(snapshot.datasetVersion!==EXPECTED_DATASET)throw new Error("KHALYON dataset hash mismatch");if(snapshot.holdoutConsumed===true)throw new Error("KHALYON holdout consumed");if(snapshot.adr!=="ADR-0002")throw new Error("KHALYON ADR mismatch");if(snapshot.historicalResultModified===true)throw new Error("KHALYON historical result modified");if(typeof snapshot.historicalVerdict!=="string"||snapshot.historicalVerdict.length===0)throw new Error("KHALYON historical verdict field unavailable");if(!/^[0-9a-f]{64}$/.test(funding.archiveSha256))throw new Error("KHALYON funding hash invalid");if(!/^sha256:[0-9a-f]{64}$/.test(funding.githubArtifactDigest))throw new Error("KHALYON funding artifact digest invalid");
for(const p of ["validation","test"]){const x=snapshot.exclusionAccounting[p];if(x.cleanEligible+x.ambiguous+x.excludedNonAmbiguous!==x.totalObservations)throw new Error("KHALYON accounting failure "+p);}
const closure=readFileSync(closurePath,"utf8");if(!closure.includes(snapshot.historicalVerdict)||!closure.includes(EXPECTED_DATASET))throw new Error("KHALYON governance source check failed");
if(!existsSync(contextPath))throw new Error("KHALYON context snapshot unavailable");const context=JSON.parse(readFileSync(contextPath,"utf8"));assertContextSnapshotHash(context);for(const p of context.provenance){if(!p.source||!p.availableAt||!/^[0-9a-f]{64}$/.test(p.sourceSnapshotHash.slice(7)))throw new Error("KHALYON context provenance invalid");}
const journal=existsSync(journalPath)?readFileSync(journalPath,"utf8").trim().split("\n").filter(Boolean).map(x=>JSON.parse(x)):[];
const tel=journal.filter(x=>x.assetId==="TEL-USDT"&&x.decision!=="ALERTE").at(-1)??null;const position={status:"UNAVAILABLE",reason:"No verified position artifact is present in this build.",source:"UNAVAILABLE"};
const runtime={source:{path:"khalyon/data/phase3-diagnostic-snapshot.json",sha256:sourceSha256,datasetVersion:snapshot.datasetVersion,adr:snapshot.adr},governance:{historical:snapshot.historicalResultModified?"MODIFIED":"FROZEN",holdout:snapshot.holdoutConsumed?"CONSUMED":"UNTOUCHED",verdict:snapshot.historicalVerdict,closureReportPath:"docs/phase3-closure-report.md",closureReportSha256:createHash("sha256").update(closure).digest("hex")},exclusionAccounting:snapshot.exclusionAccounting,historicalReference:snapshot.historicalReference,funding:{archiveSha256:funding.archiveSha256,githubArtifactDigest:funding.githubArtifactDigest},context:{snapshotHash:context.snapshotHash,runId:context.runId,asOf:context.asOf,market:context.market,macro:context.macro,liquidity:context.liquidity,events:context.events,provenance:context.provenance},surveillance:{state:tel?.decision??"UNAVAILABLE",recordedAt:tel?.recordedAt??null,reasons:tel?.reasons??["UNAVAILABLE"],checklist:{journalStateAvailable:tel!==null,holdoutUntouched:snapshot.holdoutConsumed===false,adrLocked:snapshot.adr==="ADR-0002",historicalVerdictVerified:snapshot.historicalVerdict==="PAS D'EDGE"},journalTail:journal.slice(-8)},decision:{state:tel?.decision??"UNAVAILABLE",reason:tel?.reasons?.[0]??"UNAVAILABLE",riskMaxPct:.005,riskMaxQuote:null,checks:{price:"UNAVAILABLE",btc:"UNAVAILABLE",macro:"UNAVAILABLE",sentiment:context.socialSentiment?.temperature??"UNAVAILABLE",risk:"UNAVAILABLE"},source:tel?"PROSPECTIVE JOURNAL":"UNAVAILABLE",asOf:tel?.recordedAt??null},position,contextExtended:{correlations:context.correlations??{},fundamentalsTel:context.fundamentalsTel??null,socialSentiment:context.socialSentiment??null},generatedAt:new Date().toISOString()};
mkdirSync(dirname(runtimePath),{recursive:true});writeFileSync(runtimePath,JSON.stringify(runtime,null,2)+"\n");console.log(JSON.stringify({status:"OK",sourceSha256,datasetVersion:snapshot.datasetVersion,holdoutConsumed:snapshot.holdoutConsumed,adr:snapshot.adr,historicalVerdict:snapshot.historicalVerdict,contextSnapshotHash:context.snapshotHash,contextRunId:context.runId,contextAsOf:context.asOf,contextUnavailable:context.provenance.filter(x=>x.status==="UNAVAILABLE").length,telState:runtime.surveillance.state,fundingArchiveSha256:funding.archiveSha256},null,2));