import{test,expect}from"@playwright/test";
const pages=["decision","position","context","journal","market","experiments","lab","nlp","diagnostics","datasets","verdicts","surveillance","governance"];
test.describe.configure({mode:"serial"});
for(const page of pages){test(`render ${page}`,async({page:browserPage})=>{await browserPage.goto(`http://127.0.0.1:4173/#${page}`,{waitUntil:"networkidle"});await expect(browserPage.locator("#app")).not.toBeEmpty();await expect(browserPage.locator("#app .badge")).toHaveCount(1);await expect(browserPage.locator("#app")).not.toContainText(/\bundefined\b|\bNaN\b/i);await expect(browserPage.locator("#freshness")).toContainText("Build:");await expect(browserPage.locator("#freshness")).toContainText("Données:");await expect(browserPage.locator("#freshness")).toHaveAttribute("data-hydrated","true");await expect(browserPage.locator("#freshness")).not.toContainText("Données générées à UNAVAILABLE");await expect(browserPage.locator("#interface-status")).toContainText("Interface chargée");await expect(browserPage.locator("#interface-status")).not.toContainText("UI OPERATIONAL");await browserPage.screenshot({path:`artifacts/khalyon-${page}.png`,fullPage:true});});}

test("valid runtime snapshot timestamp is displayed after hydration",async({page})=>{const generatedAt="2026-10-10T21:30:00.000Z";await page.route("**/data/runtime.json",async route=>{const response=await route.fetch();const data=await response.json();data.generatedAt=generatedAt;await route.fulfill({response,body:JSON.stringify(data)});});await page.route("**/build-manifest.json",async route=>{const response=await route.fetch();const data=await response.json();data.builtAt="2026-10-10T21:00:00.000Z";await route.fulfill({response,body:JSON.stringify(data)});});await page.goto("http://127.0.0.1:4173/#decision",{waitUntil:"networkidle"});await expect(page.locator("#freshness")).toContainText("Build: 2026-10-10 21:00:00 UTC");await expect(page.locator("#freshness")).toContainText("Données: 2026-10-10 21:30:00 UTC");await expect(page.locator("#freshness")).toHaveAttribute("data-data-timestamp",generatedAt);await expect(page.locator("#freshness")).not.toContainText("UNAVAILABLE");});

test("stale generated data is UNAVAILABLE, not a plausible timestamp",async({page})=>{await page.route("**/data/runtime.json",async route=>{const response=await route.fetch();const data=await response.json();data.generatedAt=new Date(Date.now()-60*60*1000).toISOString();await route.fulfill({response,body:JSON.stringify(data)});});await page.goto("http://127.0.0.1:4173/#decision",{waitUntil:"networkidle"});await expect(page.locator("#freshness")).toContainText("Données: UNAVAILABLE");await expect(page.locator("#freshness")).toHaveAttribute("data-data-timestamp","UNAVAILABLE");});

test("missing or invalid generatedAt is UNAVAILABLE after hydration",async({page})=>{for(const mode of ["missing","invalid"]){await page.route("**/data/runtime.json",async route=>{const response=await route.fetch();const data=await response.json();if(mode==="missing")delete data.generatedAt;else data.generatedAt="not-a-timestamp";await route.fulfill({response,body:JSON.stringify(data)});});await page.goto("http://127.0.0.1:4173/#decision",{waitUntil:"networkidle"});await expect(page.locator("#freshness")).toContainText("Données: UNAVAILABLE");await expect(page.locator("#freshness")).toHaveAttribute("data-data-timestamp","UNAVAILABLE");await page.unroute("**/data/runtime.json");}});

test("position data stays in browser localStorage",async({page})=>{await page.goto("http://127.0.0.1:4173/#position",{waitUntil:"networkidle"});await page.locator("#pos-entry").fill("0.001");await page.locator("#pos-qty").fill("1000");await page.locator("#pos-fees").fill("0.25");await page.getByText("Enregistrer localement").click();const saved=await page.evaluate(()=>localStorage.getItem("khalyon-position-v1"));expect(JSON.parse(saved)).toMatchObject({entry:0.001,qty:1000,fees:0.25});});
