import type { EntryQuality, SpotRiskResult, SwingDecision } from "./tel-swing.js";
export interface TelTestScreenInput { readonly asOf:string; readonly decision:SwingDecision; readonly quality:EntryQuality; readonly btcStatus:"OK"|"BLOCKED"|"UNAVAILABLE"; readonly macroStatus:"OK"|"UNAVAILABLE"; readonly sentimentStatus:"OK"|"UNAVAILABLE"; readonly risk:SpotRiskResult; readonly riskMaxPct:number; readonly reason:string; readonly angles?:readonly {readonly angle:string;readonly mode:string;readonly status:string;readonly detail:string}[]; readonly secondaryDerivatives?: {readonly fundingRate:number|null;readonly fundingStatus:"OK"|"UNAVAILABLE";readonly openInterestQuote:number|null;readonly openInterestStatus:"OK"|"UNAVAILABLE"}; }
export function renderTelTestScreen(input:TelTestScreenInput):string{
  const checks=[
    ["Prix étiré ?",input.quality.decision==="ACCEPTABLE"?"OK":"BLOC"],
    ["BTC ?",input.btcStatus==="OK"?"OK":"BLOC"],
    ["Macro / calendrier ?",input.macroStatus==="OK"?"OK":"BLOC"],
    ["Sentiment ?",input.sentimentStatus==="OK"?"OK":"BLOC"],
    ["Taille + stop ?",input.risk.allowed?"OK":"BLOC"]
  ];
  const rows=checks.map(([label,status])=>`<li><b>${status}</b> ${label}</li>`).join("");
  const angleRows=(input.angles??[]).map(a=>`<li><b>${a.status}</b> <span>${a.mode}</span> ${a.angle} — ${a.detail}</li>`).join("");
  const riskPct=(input.risk.riskBudgetQuote>0?input.risk.riskBudgetQuote:"0").toString();
  const derivatives=input.secondaryDerivatives;
  const fundingValue=derivatives?.fundingStatus==="OK"&&derivatives.fundingRate!==null?(derivatives.fundingRate*100).toLocaleString("fr-FR",{maximumFractionDigits:5})+" %":"UNAVAILABLE";
  const openInterestValue=derivatives?.openInterestStatus==="OK"&&derivatives.openInterestQuote!==null?derivatives.openInterestQuote.toLocaleString("fr-FR",{maximumFractionDigits:2})+" USDT":"UNAVAILABLE";
  const derivativesCard=derivatives?'<div class="card"><h2>Dérivés TEL MEXC — secondaire</h2><ul class="checks"><li><b>'+fundingValue+'</b> Funding TEL_USDT</li><li><b>'+openInterestValue+'</b> Open interest notionnel</li></ul><p class="muted">Information descriptive uniquement. Ne déclenche ni ne lève aucun veto et ne remplace pas la liquidité SPOT.</p></div>':"";
  const counterSignals=(input.angles??[]).filter(a=>a.status!=="OK").map(a=>`<li><b>${a.status}</b> ${a.angle} — ${a.detail}</li>`).join("");
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Puis-je acheter maintenant ?</title><style>*{box-sizing:border-box}body{margin:0;background:#0b0d10;color:#eef2f6;font:16px system-ui,sans-serif}main{max-width:520px;margin:auto;padding:14px}.card{background:#151922;border:1px solid #28303b;border-radius:16px;padding:16px;margin:10px 0}.state{font-size:38px;font-weight:900}.test{font-weight:800}.muted{color:#9aa6b2}.checks{list-style:none;padding:0}.checks li{padding:10px 0;border-bottom:1px solid #28303b}.risk{font-size:18px}</style></head><body><main><div class="card"><h1>Puis-je acheter maintenant ?</h1><div class="test">EN TEST — SANS ARGENT</div><div class="muted">SPOT · poche SWING uniquement</div><p class="muted">Données observées : ${input.asOf} (UTC)</p></div><div class="card"><div class="state">${input.decision}</div><div>${input.reason}</div><div class="muted">Entrée redevient acceptable sous/à: ${input.quality.acceptableMaxEntry??"UNAVAILABLE"}</div></div><div class="card"><h2>5 vérifications</h2><ul class="checks">${rows}</ul></div><div class="card"><h2>Contre-signaux / invalidation</h2><ul class="checks">${counterSignals||"<li>Aucun contre-signal détecté parmi les angles évalués.</li>"}</ul></div><div class="card"><h2>Provenance des angles</h2><ul class="checks">${angleRows}</ul></div>${derivativesCard}<div class="card risk"><b>Risque max</b><br>${riskPct} quote · ${(input.riskMaxPct*100).toFixed(2)} % du capital SWING</div><div class="card muted">Les statistiques sont historiques et descriptives, pas une prévision. Aucun ordre n'est exécuté.</div></main></body></html>`;
}